export const initialData = {
  boards: [
    {
      id: "board-1",
      columnOrder: ["column-1", "column-2", "column-3"],
      columns: [
        {
          id: "column-1",
          boardId: "board-1",
          title: "To do column",
          taskOrder: [
            "task-1",
            "task-2",
            "task-3",
            "task-4",
            "task-5",
            "task-6",
            "task-7",
          ],
          tasks: [
            {
              id: "task-1",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of task 1",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover:
                "https://images.unsplash.com/photo-1663335468790-cf7e8a1e0e73?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1121&q=80",
              priority: "low",
              approve: "Tuấn",
            },
            {
              id: "task-2",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of task 2",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover:
                "https://images.unsplash.com/photo-1663335468790-cf7e8a1e0e73?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1121&q=80",
              priority: "medium",
              approve: "Tuấn",
            },
            {
              id: "task-3",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of task 3",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "high",
              approve: "Tuấn",
            },
            {
              id: "task-4",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of task 4",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "low",
              approve: "Tuấn",
            },
            {
              id: "task-5",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of task 5",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "low",
              approve: "Tuấn",
            },
            {
              id: "task-6",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of task 6",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "low",
              approve: "Tuấn",
            },
            {
              id: "task-7",
              boardId: "board-1",
              columnId: "column-1",
              title: "Title of task 7",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "low",
              approve: "Tuấn",
            },
          ],
        },
        {
          id: "column-2",
          boardId: "board-1",
          title: "Inprogress column",
          taskOrder: ["task-8", "task-9", "task-10"],
          tasks: [
            {
              id: "task-8",
              boardId: "board-1",
              columnId: "column-2",
              title: "Title of task 8",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "low",
              approve: "Tuấn",
            },
            {
              id: "task-9",
              boardId: "board-1",
              columnId: "column-2",
              title: "Title of task 9",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "low",
              approve: "Tuấn",
            },
            {
              id: "task-10",
              boardId: "board-1",
              columnId: "column-2",
              title: "Title of task 10",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "low",
              approve: "Tuấn",
            },
          ],
        },
        {
          id: "column-3",
          boardId: "board-1",
          title: "Done column",
          taskOrder: ["task-11", "task-12", "task-13"],
          tasks: [
            {
              id: "task-11",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of task 11",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "low",
              approve: "Tuấn",
            },
            {
              id: "task-12",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of task 12",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "low",
              approve: "Tuấn",
            },
            {
              id: "task-13",
              boardId: "board-1",
              columnId: "column-3",
              title: "Title of task 13",
              description: "Cụ thể những việc phải làm để hoàn thành công việc",
              cover: null,
              priority: "low",
              approve: "Tuấn",
            },
          ],
        },
      ],
    },
  ],
};
